ALTER TABLE promptoon_cut
  ADD COLUMN IF NOT EXISTS dialog_anchor_x TEXT NOT NULL DEFAULT 'left',
  ADD COLUMN IF NOT EXISTS dialog_anchor_y TEXT NOT NULL DEFAULT 'bottom',
  ADD COLUMN IF NOT EXISTS dialog_offset_x DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dialog_offset_y DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dialog_text_align TEXT NOT NULL DEFAULT 'left';
